#pragma once

#include "ecs/components/component_set.h"
#include "ecs/archetype.h"

#include "lib/ptr.h"
#include "lib/vector.h"

namespace ag
{
	class query_tree
	{
	public:

		/// TODO: Our query tree is actually equal to the naive DAG generated by system_scheduler.
		// Need a way to easily transform format or something
		struct node
		{
			vector<archetype*> archetypes;
			vector<node*> children;
		};
	private:
		
	};
}